name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: corp-dev-eks
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps
